### ISSUE TITLE
jd: command not found

### ISSUE THREAD

**Issue by mnpenner** [maxlath/backup-github-repo#4]
First off, you rock!

This is the least fuss issue backup tool I've found so far. Others require you to set up databases and hosts and all kinds of junk.

It seems to have produced a nice `data.json` file but the last thing it said was

> /usr/bin/download-github-repo-html: line 13: jd: command not found

What's `jd`? Is the backup incomplete? What else does it need to do? How might one install `jd` on Ubuntu?

**Comment by maxlath** [comment]
thanks! that's always a good first sentence to start the day ^^

`jd` was referring to [jsondepth](https://www.npmjs.com/package/jsondepth), but my assumption that running `npm install` in the local `backup-github-repo` repo was making `jd` accessible to the executables defined in package.json proved wrong, so I replaced it by the more wild spread [jq](https://stedolan.github.io/jq/) (9b2ff00) and made the dependency explicit in the readme.

fyi, I also pushed a few other updates, including one that fixes in an issue with the css assets (806040e)

**Comment by mnpenner** [comment]
Thanks for the update! I already do have `jq` installed 😄 Hadn't heard of jsondepth.

I updated to the latest version and tried again. I'm seeing a new error now:

```
...
[99/99]: https://github.com/my/repo/issues/99 --> 99.html
Done downloading issues and pull requests HTML sequentially
Padding filenames with zeros
Download stylesheets
Download images
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
couldn't fetch  and put it into assets/adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
```

Which is kind of strange actually because the file did get created:

```
❯ ll repo-backup/html/assets
-rwxrwxrwx 1 mpen mpen 0 Dec  2 00:10 adc83b19e793491b1c6ea0fd8b46cd9f32e592fc*
```

**Comment by maxlath** [comment]
If it's a public repo, which one is it? I could try to reproduce the error
