### ISSUE TITLE
Clarify necessity of `npm link`

### ISSUE THREAD

**Issue by goretkin** [maxlath/backup-github-repo#5]
From the description

```
# Make backup-github-repo available globally
npm link
```

I thought I could get away with not doing `npm link` if I wanted to invoke the tool with the full path. However [`backup-github-repo`](https://github.com/maxlath/backup-github-repo/blob/5e667cff9c1c35abc9fb65cd28d6222e44c95d05/bin/backup_github_repo) itself assumes `npm link` has been run and that `PATH` contains symlinks, for example:

```
/usr/local/bin/download-github-repo-json@ -> ../lib/node_modules/backup-github-repo/scripts/download_json
```

**Comment by maxlath** [comment]
clarification attempted in 62ef2a4
